spring.application.name=digital-wallet
spring.datasource.username=root
spring.datasource.password=
spring.datasource.url=jdbc:mysql://localhost:3306/digital_wallet


# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.open-in-view=false

security.jwt.secret-key=baf701e959a2230649d6e171e8bc929e2b62284f1b251bb052a4be0a10bae372
# 1h in millisecond
security.jwt.expiration-time=3600000